language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer require satooshi/php-coveralls:dev-master --no-update --dev
  - composer install --prefer-source
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then pyrus install pear/PHP_CodeSniffer; fi;'
  - phpenv rehash

script:
  - mkdir -p build/logs
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpcs --standard=psr2 src/; fi;'
  - phpunit --coverage-text

after_script:
  - php vendor/bin/coveralls

matrix:
  allow_failures:
    - php: hhvm
