language: php

# list any PHP version you want to test against
php:
  - 5.4
  - 5.5
  - hhvm

before_script:
  - composer self-update
  - composer require satooshi/php-coveralls:dev-master --no-update --dev
  - composer install --dev --prefer-source
  - phpenv rehash

script:
  - mkdir -p build/logs

after_script:
  - php vendor/bin/coveralls
