language: php
sudo: false
cache:
    directories:
        - "$HOME/.composer/cache"
matrix:
    include:
        - php: 7.2
          env:
              - COMPOSER_ARGS="--no-interaction --no-suggest --prefer-source --prefer-lowest --prefer-stable"
              - RUN_PHPSTAN=false
              - VALIDATE_CODING_STYLE=false
        - php: 7.2
          env:
              - COMPOSER_ARGS="--no-interaction --no-suggest --prefer-source"
              - RUN_PHPSTAN=false
              - VALIDATE_CODING_STYLE=false
        - php: 7.3
          env:
              - COMPOSER_ARGS="--no-interaction --no-suggest --prefer-source --prefer-lowest --prefer-stable"
              - RUN_PHPSTAN=false
              - VALIDATE_CODING_STYLE=false
        - php: 7.3
          env:
              - COMPOSER_ARGS="--no-interaction --no-suggest --prefer-source"
              - RUN_PHPSTAN=false
              - VALIDATE_CODING_STYLE=false
        - php: 7.4
          env:
              - COMPOSER_ARGS="--no-interaction --no-suggest --prefer-source --prefer-lowest --prefer-stable"
              - RUN_PHPSTAN=false
              - VALIDATE_CODING_STYLE=false
        - php: 7.4
          env:
              - COMPOSER_ARGS="--no-interaction --no-suggest --prefer-source"
              - RUN_PHPSTAN=true
              - VALIDATE_CODING_STYLE=true
        - php: nightly
          env:
              - COMPOSER_ARGS="--no-interaction --no-suggest --prefer-source"
              - RUN_PHPSTAN=false
              - VALIDATE_CODING_STYLE=false
          install:
              - composer remove --no-interaction --no-update --dev "friendsofphp/php-cs-fixer"
              - travis_retry composer update $COMPOSER_ARGS
    allow_failures:
        - php: nightly
    fast_finish: true
before_install:
    - travis_retry composer self-update
install:
    - travis_retry composer update $COMPOSER_ARGS
script:
    - if [ "$VALIDATE_CODING_STYLE" == "true" ]; then composer phpcs; fi
    - if [ "$RUN_PHPSTAN" == "true" ]; then composer phpstan; fi
    - composer phpunit
